USE ATOMIC_RESTAURANTE;

GO
--Clases de Cuentas por default

INSERT INTO CONTABILIDAD_CLASE_CUENTA(IdClasCuenta,NombClasC)
VALUES(1,'ACTIVOS'),(2,'PASIVOS'),(3,'PATRIMONIOS Y RESERVAS')

INSERT INTO CONTABILIDAD_CLASE_CUENTA(IdClasCuenta,NombClasC)
VALUES(4,'INGRESOS'),(5,'GASTPS'),(6,'COSTOS DE VENTA'),(7,'COSTOS DE PRODUCCION')

INSERT INTO CONTABILIDAD_CLASE_CUENTA(IdClasCuenta,NombClasC)
VALUES(8,'CUENTAS DE ORDEN DEUDORAS'),(9,'Cuentas de Orden acreedoras')

GO
--	Grupos de Cuentas por Default
--// Grupos para ACTIVOS => 1
INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(1,1,'ACTIVO CIRCULANTE'),(1,2,'ACTIVO NO CIRCULANTE'),(1,3,'OTROS ACTIVOS')

INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(2,1,'PASIVO CIRCULANTE'),(2,2,'PASIVO NO CIRCULANTE')

INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(3,1,'CAPITAL SOCIAL'),(3,2,'RESERVAS'),(3,3,'REVALUACIONES'),(3,9,'RESULTADOS DEL EJERCICIO')

INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(4,1,'INGRESOS OPERACIONALES'),(4,2,'INGRESOS NO OPERACIONALES'),(4,3,'OTROS INGRESOS')

INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(5,1,'GASTOS OPERACIONALES'),(5,2,'GASTOS ADMINISTRATIVOS'),(5,3,'GASTOS PUBLICOS'),
(5,8,'OTROS GASTOS'),(5,9,'CIERRE DE GASTOS')

INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(6,1,'COSTO DE VENTA PRODUCTOS'),(6,2,'COSTO DE VENTA SERVICIOS'),(6,8,'OTROS COSTOS')

INSERT INTO CONTABILIDAD_GRUPO_CUENTA(IdClasCuenta,IdGrupo, NombGrupo)
VALUES(7,1,'COSTO PRODUCCION INSUMOS'),(7,2,'COSTO PRODUCCION PRODUCTOS'),(7,8,'OTROS COSTOS PRODUCCION')


