USE ATOMIC_RESTAURANTE;
GO

ALTER TABLE dbo.CONTABILIDAD_GASTO
DROP CONSTRAINT FK_Tipo_de_Gasto
	
GO

ALTER TABLE  dbo.CONTABILIDAD_DOCUMENTO 
DROP CONSTRAINT FK_Contabilidad_Documento_Tipo


GO
IF OBJECT_ID('dbo.CONTABILIDAD_TIPO_MOVIMIENTO_SUBCUENTA') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_TIPO_MOVIMIENTO_SUBCUENTA
GO
CREATE	 TABLE CONTABILIDAD_TIPO_MOVIMIENTO_SUBCUENTA (
	IdTipMov			TINYINT		IDENTITY(1,1),
	NombTipMov			NVARCHAR(100)	NOT NULL	UNIQUE,
	DescTipMov			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Tipo_Movimiento_Cuenta	PRIMARY KEY(IdTipMov)
);
GO

IF OBJECT_ID('dbo.CONTABILIDAD_MOVIMIENTO_SUBCUENTA') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_MOVIMIENTO_SUBCUENTA
GO
CREATE TABLE	dbo.CONTABILIDAD_MOVIMIENTO_SUBCUENTA	(
	IdMovimiento		INT			IDENTITY(1,1),
	IdTipMov			TINYINT		NOT NULL,
	NumSubCuenta		NVARCHAR(6) NOT NULL,
	IdDocumento			INT			NOT NULL,
	IdMoneda			TINYINT			NOT NULL,
	FechaMovimiento		SMALLDATETIME	NOT NULL,
	Debe				NUMERIC(17,5)	NOT NULL,
	DebeMonLocal		NUMERIC(17,5)	NOT NULL,
	Haber				NUMERIC(17,5)	NOT NULL,
	HaberMonLocal		NUMERIC(17,5)	NOT NULL,
	Saldo				NUMERIC(17,5)	NULL,
	SalgoMonLoca		NUMERIC(17,5)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Movimiento_Cuenta	PRIMARY KEY(IdMovimiento),
	CONSTRAINT	FK_Moneda_Movimiento_SubCuenta		FOREIGN KEY(IdMoneda)
				REFERENCES dbo.FACTURACION_MONEDA(IdMoneda),
	CONSTRAINT	FK_Contabilidad_SubCuenta_Movimiento		FOREIGN KEY(NumSubCuenta)
				REFERENCES	dbo.CONTABILIDAD_SUBCUENTA(NumSubCuenta)
);
GO

IF OBJECT_ID('dbo.CONTABILIDAD_TIPO_DE_GASTO') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_TIPO_DE_GASTO
GO
CREATE TABLE	dbo.CONTABILIDAD_TIPO_DE_GASTO (
	IdTipGasto			TINYINT		IDENTITY(1,1),
	NombTipGas			NVARCHAR(100)	NOT NULL,
	DescTipGas			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Tipo_de_Gasto		PRIMARY KEY(IdTipGasto)
);

SET IDENTITY_INSERT CONTABILIDAD_TIPO_DE_GASTO ON;

INSERT INTO CONTABILIDAD_TIPO_DE_GASTO(IdTipGasto, NombTipGas, DescTipGas)
VALUES(1,'Gastos Fijos','Son aquellos gastos que siempre van a estar mes a mes y que a largo plazo no cambiarán.'),(2,'Gastos Variables','Como lo indica su nombre, varían ya sea en semanas o meses.'),(3,'Gastos Inesperados','Se usa para definir dentro del presupuesto un gasto eventual.')

SET IDENTITY_INSERT CONTABILIDAD_TIPO_DE_GASTO OFF;
GO

IF OBJECT_ID('dbo.CONTABILIDAD_GASTO') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_GASTO
GO
CREATE TABLE	dbo.CONTABILIDAD_GASTO (
	IdGasto				INT		IDENTITY(1,1),
	IdRestaurante		TINYINT			NOT NULL,
	IdTipGasto			TINYINT			NOT NULL,
	IdUsuario			INT				NOT NULL,
	NReferencia			NVARCHAR(20)	NULL,
	Serie				NVARCHAR(10)	NULL,
	NumDoc				NVARCHAR(10)	NULL,
	Concepto			NVARCHAR(250)	NOT	NULL,
	SubTotal			NUMERIC(17,7)	NOT NULL,
	IvaTotal			NUMERIC(17,7)	NOT NULL,
	TotalNeto			NUMERIC(17,7)	NOT NULL,
	FechaGasto			SMALLDATETIME	NOT NULL,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT			PK_Contabilidad_Gasto	PRIMARY KEY(IdGasto),
	CONSTRAINT			FK_Tipo_de_Gasto		FOREIGN KEY(IdTipGasto)
				REFERENCES	dbo.CONTABILIDAD_TIPO_DE_GASTO (IdTipGasto),
	CONSTRAINT			FK_Usuario_Gasto		FOREIGN KEY(IdUsuario)
				REFERENCES	dbo.USUARIO	(IdUsuario)
);

IF OBJECT_ID('dbo.CONTABILIDAD_TIPO_CIERRES') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_TIPO_CIERRES
GO
CREATE TABLE dbo.CONTABILIDAD_TIPO_CIERRES (
	IdTipC			TINYINT		IDENTITY(1,1),
	NombTipC		NVARCHAR(50)	NOT NULL	UNIQUE,
	Habilitado		BIT				NOT NULL	DEFAULT 1,
	CreatedAt		SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt		SMALLDATETIME	NULL,
	CONSTRAINT		PK_Contabilidad_Tipo_Cierre		PRIMARY KEY(IdTipC)
);


GO
IF OBJECT_ID('dbo.CONTABILIDAD_TIPO_DOCUMENTO') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_TIPO_DOCUMENTO
GO
CREATE TABLE dbo.CONTABILIDAD_TIPO_DOCUMENTO (
	IdTipDoc	TINYINT		IDENTITY(1,1),
	NombTipDoc	NVARCHAR(50)	NOT NULL,
	DescTipDoc	NVARCHAR(150)	NULL,
	Habilitado	BIT				NOT NULL DEFAULT 1,
	CreatedAt	SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	UpdatedAt	SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_TipDoc	PRIMARY KEY(IdTipDoc),
	CONSTRAINT	U_Contabilidad_Cuenta_Nombre	UNIQUE(NombTipDoc)
);	



IF OBJECT_ID('dbo.CONTABILIDAD_DOCUMENTO') IS NOT NULL
	DROP TABLE dbo.CONTABILIDAD_DOCUMENTO
GO
--Un documento puede afectar multiples cuentas
CREATE TABLE dbo.CONTABILIDAD_DOCUMENTO ( 
	IdDocumento		TINYINT		IDENTITY(1,1),
	IdTipDoc		TINYINT			NOT NULL,
	IdRestaurante	INT				NOT NULL,
	IdSucursal		INT				NULL,
	IdMoneda		TINYINT			NOT NULL,
	Serie			NVARCHAR(10)	NOT NULL,
	NumDoc			INT				NOT NULL,
	NombDoc			NVARCHAR(50)	NOT NULL,
	DescDoc			NVARCHAR(150)	NULL,
	Habilitado		BIT				NOT NULL DEFAULT 1,
	CreatedAt	SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	UpdatedAt	SMALLDATETIME	NULL,
	CONSTRAINT PK_Contabilidad_Documento	PRIMARY KEY(IdDocumento),
	CONSTRAINT FK_Contabilidad_Documento_Tipo	FOREIGN KEY(IdTipDoc)	
				REFERENCES dbo.CONTABILIDAD_TIPO_DOCUMENTO(IdTipDoc),
	CONSTRAINT FK_Restaurante_Documento			FOREIGN KEY(IdRestaurante)
				REFERENCES dbo.RESTAURANTE(IdRestaurante),
	CONSTRAINT FK_Sucursal_Documento			FOREIGN KEY(IdSucursal)
				REFERENCES dbo.SUCURSAL_RESTAURANTE(IdSucursal),
	CONSTRAINT FK_Moneda_Documento			FOREIGN KEY(IdMoneda)
				REFERENCES	dbo.FACTURACION_MONEDA(IdMoneda)
);

