USE ATOMIC_RESTAURANTE;

GO
IF OBJECT_ID('USP_CREATE_CONTABILIDAD_DOCUMENTO','P') IS NOT NULL
	DROP PROCEDURE USP_CREATE_CONTABILIDAD_DOCUMENTO;
GO
CREATE PROCEDURE USP_CREATE_CONTABILIDAD_DOCUMENTO (
	@IdTipDoc		TINYINT,
	@IdRestaurante	INT,
	@IdSucursal		INT,
	@IdMoneda		INT,
	@Serie			NVARCHAR(10),
	@NumDoc			INT,
	@NombDoc		NVARCHAR(50),
	@DescDoc		NVARCHAR(150),
	@IdDocumento	TINYINT	OUT
)
AS BEGIN
	INSERT INTO dbo.CONTABILIDAD_DOCUMENTO(IdTipDoc,IdRestaurante,IdSucursal, IdMoneda, Serie, NumDoc, NombDoc, DescDoc)
	VALUES(@IdTipDoc, @IdRestaurante, @IdSucursal, @IdMoneda, @Serie, @NumDoc, @NombDoc, @DescDoc)
	SET @IdDocumento = @@IDENTITY
END

GO
IF OBJECT_ID('USP_UPDATE_CONTABILIDAD_DOCUMENTO','P') IS NOT NULL
	DROP PROCEDURE USP_UPDATE_CONTABILIDAD_DOCUMENTO;
GO
CREATE PROCEDURE USP_UPDATE_CONTABILIDAD_DOCUMENTO (
	@IdDocumento	TINYINT,
	@IdSucursal		INT,
	@IdMoneda		INT,
	@NombDoc		NVARCHAR(50),	
	@DescDoc		NVARCHAR(150)
)
AS BEGIN

	UPDATE dbo.CONTABILIDAD_DOCUMENTO SET IdSucursal = @IdSucursal, IdMoneda = @IdMoneda, NombDoc = @NombDoc, DescDoc = @DescDoc
	WHERE IdDocumento = @IdDocumento
END 