IF OBJECT_ID('USP_GET_PRODUCTOS_MAS_COMPRADOS','P') IS NOT NULL
	DROP PROCEDURE USP_GET_PRODUCTOS_MAS_COMPRADOS
GO
CREATE PROCEDURE USP_GET_PRODUCTOS_MAS_COMPRADOS
AS BEGIN
	IF OBJECT_ID('tempdb..#TMP') IS NOT NULL
	DROP TABLE #TMP
	
	SELECT DET.IdProducto
			, PRO.NombProducto
			, conteo = SUM(DET.Cantidad)
			, PRO.IdProveedor
	INTO	#TMP
	FROM	dbo.FACTURA_COMPRA FACT
			INNER JOIN dbo.DETALLE_FACTURA_COMPRA DET
				ON FACT.IdFactura = DET.IdFactura
			INNER JOIN dbo.PRODUCTO PRO
				ON DET.IdProducto = PRO.IdProducto
	GROUP BY DET.IdProducto
			, PRO.NombProducto
			, PRO.IdProveedor
	ORDER BY SUM(DET.Cantidad) DESC


	SELECT	TOP	5
			IdProducto
			, NombProducto
			, Proveedor = PROV.NombProveedor
			, Cantidad = CAST(conteo AS INT)
	FROM	#TMP TEMP
			INNER JOIN PROVEEDOR PROV
				ON TEMP.IDPROVEEDOR = PROV.IDPROVEEDOR
	ORDER BY TEMP.CONTEO DESC
	
END
