IF OBJECT_ID('UFN_CHECK_ESTADO_EMPAQUE','FN') IS NOT NULL
	DROP FUNCTION UFN_CHECK_ESTADO_EMPAQUE
GO
CREATE FUNCTION UFN_CHECK_ESTADO_EMPAQUE(
	@IdProducto INT,
	@Cantidad INT
)
RETURNS INT
AS
BEGIN
	DECLARE @CANTIDAD_ESPERADA INT;
	DECLARE @RETORNO INT;
	SELECT @CANTIDAD_ESPERADA = CantidadEmpaque 
	FROM dbo.PRODUCTO 
		WHERE IdProducto = @IdProducto;
	IF @CANTIDAD_ESPERADA = NULL
		SET @RETORNO= 3;
	ELSE IF @CANTIDAD_ESPERADA = @Cantidad
		SET @RETORNO = 1;
	ELSE
		SET @RETORNO= 2;
	RETURN @RETORNO;
END

