USE ATOMIC_RESTAURANTE ;
GO
CREATE PROCEDURE USP_DELETE_ALL_F_CONSTRAINT_TABLE(@TABLE VARCHAR(100))
AS 
BEGIN
	SET NOCOUNT ON

	DECLARE  @constraintname SYSNAME, @objectid int,
			@sqlcmd         VARCHAR(1024)

	DECLARE CONSTRAINTSCURSOR CURSOR  FOR
	SELECT	NAME, parent_object_id 
	FROM	SYS.OBJECTS 
	WHERE	TYPE = 'F' 
			AND parent_object_id = OBJECT_ID(@TABLE)

	OPEN CONSTRAINTSCURSOR

	FETCH NEXT FROM CONSTRAINTSCURSOR
	INTO @constraintname, @objectid

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
	SELECT @sqlcmd = 'ALTER TABLE ' + OBJECT_NAME(@objectid) + ' DROP CONSTRAINT ' + @constraintname
	EXEC( @sqlcmd)
	FETCH NEXT FROM CONSTRAINTSCURSOR
	INTO @constraintname, @objectid
	END

	CLOSE CONSTRAINTSCURSOR
	DEALLOCATE CONSTRAINTSCURSOR
END