use ATOMIC_RESTAURANTE;

GO

EXEC USP_DELETE_ALL_F_CONSTRAINT_TABLE 'dbo.ROL_RECURSO_SISTEMA'
EXEC USP_DELETE_ALL_F_CONSTRAINT_TABLE 'dbo.RECURSO_SISTEMA'

GO

IF OBJECT_ID('dbo.RECURSO_SISTEMA') IS NOT NULL
	DROP TABLE dbo.RECURSO_SISTEMA

CREATE TABLE dbo.RECURSO_SISTEMA(
	IdRecursoSistema INT IDENTITY(1,1)
	, IdMenuPadre INT NULL
	, Nombre VARCHAR(50) NOT NULL
	, Descripcion VARCHAR(300) NOT NULL
	, Ruta VARCHAR(1000) 
	, Icono VARCHAR(100)
	, Clase VARCHAR(100)
	, Orden INT NULL
	, Habilitado BIT NOT NULL DEFAULT 1
	, CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
	, UpdateAt DATETIME NULL

	CONSTRAINT PK_IdRecursoSistema PRIMARY KEY(IdRecursoSistema)
)

IF OBJECT_ID('dbo.ROL_RECURSO_SISTEMA') IS NOT NULL
	DROP TABLE dbo.ROL_RECURSO_SISTEMA

CREATE TABLE dbo.ROL_RECURSO_SISTEMA(
	IdRolRecursoSistema INT IDENTITY(1,1)
	, IdRol TINYINT  NOT NULL
	, IdRecursoSistema INT NOT NULL
	, Habilitado BIT NOT NULL DEFAULT 1
	, CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
	, UpdateAt DATETIME NULL

	CONSTRAINT PK_IdRolRecursoSistema PRIMARY KEY(IdRolRecursoSistema)
	, CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (IdRol) REFERENCES ROL_USUARIO(IdRol)
	, CONSTRAINT FK_RECURSO_SISTEMA FOREIGN KEY (IdRecursoSistema) REFERENCES RECURSO_SISTEMA(IdRecursoSistema)
)

