USE ATOMIC_RESTAURANTE

GO

IF OBJECT_ID('dbo.BITACORA_CAMBIOS_FACTURA') IS NOT NULL
	DROP TABLE dbo.BITACORA_CAMBIOS_FACTURA

GO
CREATE TABLE dbo.BITACORA_CAMBIOS_FACTURA(
	IdConsecutivo INT IDENTITY(1,1)
	, IdFactura INT NOT NULL
	, IdUsuario INT NOT NULL
	, Descripcion VARCHAR(300) NOT NULL
	, CreatedAt DATETIME NOT NULL

	CONSTRAINT PK_ConsecutivoBitacora	PRIMARY KEY (IdConsecutivo), 
	CONSTRAINT FK_IdFacturaBitacora		FOREIGN KEY (IdFactura) 
				REFERENCES FACTURA_COMPRA(IdFactura), 
	CONSTRAINT FK_IdUsuarioBitacora		FOREIGN KEY (IdUsuario) 
			REFERENCES USUARIO(IdUsuario)
)

GO

USE master;