USE ATOMIC_RESTAURANTE;

GO
CREATE TABLE	CONTABILIDAD_TIPO_DE_GASTO (
	IdTipGasto			TINYINT		IDENTITY(1,1),
	NombTipGas			NVARCHAR(100)	NOT NULL,
	DescTipGas			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Tipo_de_Gasto		PRIMARY KEY(IdTipGasto)
);

GO
CREATE TABLE	CONTABILIDAD_GASTO (
	IdGasto				INT		IDENTITY(1,1),
	IdTipGasto			TINYINT			NOT NULL,
	IdUsuario			INT				NOT NULL,
	NReferencia			NVARCHAR(20)	NULL,
	Serie				NVARCHAR(10)	NULL,
	NumDoc				NVARCHAR(10)	NULL,
	Concepto			NVARCHAR(250)	NOT	NULL,
	SubTotal			NUMERIC(17,7)	NOT NULL,
	IvaTotal			NUMERIC(17,7)	NOT NULL,
	TotalNeto			NUMERIC(17,7)	NOT NULL,
	FechaGasto			SMALLDATETIME	NOT NULL,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT			PK_Contabilidad_Gasto	PRIMARY KEY(IdGasto),
	CONSTRAINT			FK_Tipo_de_Gasto		FOREIGN KEY(IdTipGasto)
				REFERENCES	dbo.CONTABILIDAD_TIPO_DE_GASTO (IdTipGasto),
	CONSTRAINT			FK_Usuario_Gasto		FOREIGN KEY(IdUsuario)
				REFERENCES	dbo.USUARIO	(IdUsuario)
);

	