USE ATOMIC_RESTAURANTE;

GO
CREATE TABLE	CONTABILIDAD_TIPO_CUENTA ( 
	IdTipCuenta			TINYINT		IDENTITY(1,1),
	NombTipC			NVARCHAR(100)	NOT NULL,
	DescTipC			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Tipo_Cuenta		PRIMARY KEY(IdTipCuenta)
);

GO
CREATE TABLE	CONTABILIDAD_CUENTA (
	IdCuenta			TINYINT		IDENTITY(1,1),
	IdTipCuenta			TINYINT		NOT NULL,
	IdRestaurante		INT			NOT NULL,
	IdSucursal			INT			NULL,
	IdMoneda			TINYINT		NOT NULL,
	NumCuenta			TINYINT		NOT NULL,
	NombCuenta			NVARCHAR(50)	NOT NULL,
	DescCuenta			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Cuenta		PRIMARY KEY(IdCuenta),
	CONSTRAINT	FK_Contabilidad_Cuenta_Tipo		FOREIGN KEY(IdTipCuenta)
				REFERENCES	dbo.CONTABILIDAD_TIPO_CUENTA(IdTipCuenta),
	CONSTRAINT	FK_Contabilidad_Moneda_Cuenta	FOREIGN KEY(IdMoneda)
				REFERENCES	dbo.FACTURACION_MONEDA(IdMoneda),
	CONSTRAINT	PK_Contabilidad_Cuenta_Restaurante	FOREIGN KEY(IdRestaurante)
				REFERENCES dbo.RESTAURANTE(IdRestaurante),
	CONSTRAINT	PK_Contabilidad_Cuenta_Sucursal		FOREIGN KEY(IdSucursal)
				REFERENCES dbo.SUCURSAL_RESTAURANTE(IdSucursal)
);
GO
CREATE	 TABLE CONTABILIDAD_TIPO_MOVIMIENTO_CUENTA (
	IdTipMov			TINYINT		IDENTITY(1,1),
	NombTipMov			NVARCHAR(100)	NOT NULL	UNIQUE,
	DescTipMov			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Tipo_Movimiento_Cuenta	PRIMARY KEY(IdTipMov)
);

GO

CREATE TABLE	CONTABILIDAD_MOVIMIENTO_CUENTA	(
	IdMovimiento		INT			IDENTITY(1,1),
	IdTipMov			TINYINT		NOT NULL,
	IdCuenta			TINYINT		NOT NULL,
	IdDocumento			INT			NOT NULL,
	IdMoneda			TINYINT			NOT NULL,
	FechaMovimiento		SMALLDATETIME	NOT NULL,
	Debe				NUMERIC(17,5)	NOT NULL,
	DebeMonLocal		NUMERIC(17,5)	NOT NULL,
	Haber				NUMERIC(17,5)	NOT NULL,
	HaberMonLocal		NUMERIC(17,5)	NOT NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Movimiento_Cuenta	PRIMARY KEY(IdMovimiento),
	CONSTRAINT	FK_Contabilidad_Movimiento_Cuenta_Tipo	FOREIGN KEY(IdTipMov)
				REFERENCES	dbo.CONTABILIDAD_TIPO_MOVIMIENTO_CUENTA(IdTipMov),
	CONSTRAINT	FK_Contabilidad_Cuenta_Movimiento		FOREIGN KEY(IdCuenta)
				REFERENCES	dbo.CONTABILIDAD_CUENTA(IdCuenta)
GO
CREATE TABLE	CONTABILIDAD_TIPO_DE_GASTO (
	IdTipGasto			TINYINT		IDENTITY(1,1),
	NombTipGas			NVARCHAR(100)	NOT NULL,
	DescTipGas			NVARCHAR(150)	NULL,
	Habilitado			BIT				NOT NULL	DEFAULT 1,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT	PK_Contabilidad_Tipo_de_Gasto		PRIMARY KEY(IdTipGasto)
);

GO
CREATE TABLE	CONTABILIDAD_GASTO (
	IdGasto				INT		IDENTITY(1,1),
	IdRestaurante		TINYINT			NOT NULL,
	IdTipGasto			TINYINT			NOT NULL,
	IdUsuario			INT				NOT NULL,
	NReferencia			NVARCHAR(20)	NULL,
	Serie				NVARCHAR(10)	NULL,
	NumDoc				NVARCHAR(10)	NULL,
	Concepto			NVARCHAR(250)	NOT	NULL,
	SubTotal			NUMERIC(17,7)	NOT NULL,
	IvaTotal			NUMERIC(17,7)	NOT NULL,
	TotalNeto			NUMERIC(17,7)	NOT NULL,
	FechaGasto			SMALLDATETIME	NOT NULL,
	CreatedAt			SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt			SMALLDATETIME	NULL,
	CONSTRAINT			PK_Contabilidad_Gasto	PRIMARY KEY(IdGasto),
	CONSTRAINT			FK_Tipo_de_Gasto		FOREIGN KEY(IdTipGasto)
				REFERENCES	dbo.CONTABILIDAD_TIPO_DE_GASTO (IdTipGasto),
	CONSTRAINT			FK_Usuario_Gasto		FOREIGN KEY(IdUsuario)
				REFERENCES	dbo.USUARIO	(IdUsuario)
);


CREATE TABLE CONTABILIDAD_TIPO_CIERRES (
	IdTipC			TINYINT		IDENTITY(1,1),
	NombTipC		NVARCHAR(50)	NOT NULL	UNIQUE,
	Habilitado		BIT				NOT NULL	DEFAULT 1,
	CreatedAt		SMALLDATETIME	NOT NULL	DEFAULT GETDATE(),
	UpdatedAt		SMALLDATETIME	NULL,
	CONSTRAINT		PK_Contabilidad_Tipo_Cierre		PRIMARY KEY(IdTipC)
);

CREATE TABLE CONTABILIDAD_DATOS_CIERRES (
	